package nl.gzmn.gZMNBuildtools.command.brush;

import java.util.Base64;

public class CodeDecoder {

    /**
     * Decodes a custom 'gzmn@...' code into a WorldEdit #gradient pattern string.
     * @param code The code generated by the web editor.
     * @return The formatted pattern string, or null if invalid.
     */
    public static String decodeToPattern(String code) {
        if (code == null || !code.startsWith("gzmn@")) {
            return null;
        }

        try {
            String base64 = code.substring(5);
            String decoded = new String(Base64.getDecoder().decode(base64));

            // Format: direction|mode|layer1|layer2|...
            String[] parts = decoded.split("\\|");

            if (parts.length < 3) {
                return null;
            }

            String direction = parts[0];
            String mode = parts[1];

            StringBuilder pattern = new StringBuilder();
            pattern.append("#gradient[").append(direction).append("][").append(mode).append("]");

            for (int i = 2; i < parts.length; i++) {
                if (!parts[i].trim().isEmpty()) {
                    pattern.append("[").append(parts[i].trim()).append("]");
                }
            }

            return pattern.toString();
        } catch (Exception e) {
            return null;
        }
    }
}
